import React, { useState, useEffect } from "react";
import {  View,  Text,  StyleSheet,  FlatList,  ActivityIndicator,  TouchableOpacity,  Alert,} from "react-native";

import { db } from "../firebaseConfig";
import { collection, getDocs } from "firebase/firestore";

import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export default function AttendanceHistoryScreen() {
  const [attendanceRecords, setAttendanceRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  const fetchAttendance = async () => {
    try {
      setLoading(true);

      const querySnapshot = await getDocs(
        collection(db, "attendance")
      );

      const data = querySnapshot.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
      }));

      // Sort newest records first
      data.sort((a, b) => {
        const dateA = `${a.date || ""} ${a.time || ""}`;
        const dateB = `${b.date || ""} ${b.time || ""}`;

        return dateB.localeCompare(dateA);
      });

      setAttendanceRecords(data);
    } catch (error) {
      console.log("Fetch attendance error:", error);

      Alert.alert(
        "Error",
        "Unable to load attendance records."
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAttendance();
  }, []);

  const escapeHtml = (value) => {
    if (value === null || value === undefined) {
      return "";
    }

    return String(value)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  };

  const exportRecordsToPDF = async () => {
    if (attendanceRecords.length === 0) {
      Alert.alert(
        "No Records",
        "There are no attendance records to export."
      );
      return;
    }

    try {
      setExporting(true);

      const rowsHtml = attendanceRecords
        .map(
          (item) =>` 
            <tr>
              <td>${escapeHtml(item.fullName)}</td>
              <td>${escapeHtml(item.matricNumber)}</td>
              <td>${escapeHtml(item.department)}</td>
              <td>${escapeHtml(item.status)}</td>
              <td>${escapeHtml(item.date)}</td>
              <td>${escapeHtml(item.time)}</td>
            </tr>
          `
        )
        .join("");

      const html = `
        <!DOCTYPE html>

        <html>
          <head>
            <meta charset="UTF-8" />

            <style>
              body {
                font-family: Arial, Helvetica, sans-serif;
                padding: 20px;
                color: #222;
              }

              h1 {
                font-size: 22px;
                margin-bottom: 5px;
              }

              .subtitle {
                color: #666;
                margin-bottom: 20px;
              }

              table {
                width: 100%;
                border-collapse: collapse;
              }

              th {
                background-color: #0B6E99;
                color: white;
                padding: 8px;
                border: 1px solid #ccc;
                text-align: left;
                font-size: 11px;
              }

              td {
                padding: 8px;
                border: 1px solid #ccc;
                font-size: 10px;
              }

              tr:nth-child(even) {
                background-color: #f5f5f5;
              }

              .footer {
                margin-top: 20px;
                font-size: 11px;
                color: #666;
              }
            </style>
          </head>

          <body>

            <h1>AttendIQ - Attendance Records</h1>

            <p class="subtitle">
              Total Records: ${attendanceRecords.length}
            </p>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Matric No.</th>
                  <th>Department</th>
                  <th>Status</th>
                  <th>Date</th>
                  <th>Time</th>
                </tr>
              </thead>

              <tbody>
                ${rowsHtml}
              </tbody>
            </table>

            <p class="footer">
              Generated by AttendIQ
            </p>

          </body>
        </html>
      `;

      console.log("Generating attendance PDF...");

      const result = await Print.printToFileAsync({
        html,
        margins: {
          top: 20,
          bottom: 20,
          left: 20,
          right: 20,
        },
      });

      console.log("PDF generated:", result.uri);

      if (!result?.uri) {
        throw new Error("PDF file was not created.");
      }

      const canShare = await Sharing.isAvailableAsync();

      if (canShare) {
        await Sharing.shareAsync(result.uri, {
          mimeType: "application/pdf",
          dialogTitle: "Export Attendance Records",
          UTI: "com.adobe.pdf",
        });
      } else {
        Alert.alert(
          "PDF Created",
          `The attendance PDF was created successfully.`
        );
      }
    } catch (error) {
      console.log("PDF export error:", error);

      Alert.alert(
        "Export Failed",
        error?.message ||
          "Something went wrong while generating the attendance PDF."
      );
    } finally {
      setExporting(false);
    }
  };

  if (loading) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator
          size="large"
          color="#0B6E99"
        />

        <Text style={styles.loadingText}>
          Loading attendance records...
        </Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>

      <View style={styles.headerRow}>

        <Text style={styles.title}>
          Attendance History
        </Text>

        <TouchableOpacity
          style={[
            styles.exportButton,
            exporting && styles.exportButtonDisabled,
          ]}
          onPress={exportRecordsToPDF}
          disabled={exporting}
        >
          {exporting ? (
            <ActivityIndicator
              size="small"
              color="#fff"
            />
          ) : (
            <Text style={styles.exportButtonText}>
              Export PDF
            </Text>
          )}
        </TouchableOpacity>

      </View>

      {attendanceRecords.length === 0 ? (
        <Text style={styles.emptyText}>
          No attendance records found.
        </Text>
      ) : (
        <FlatList
          data={attendanceRecords}
          keyExtractor={(item) => item.id}
          showsVerticalScrollIndicator={false}
          contentContainerStyle={styles.listContent}
          renderItem={({ item }) => (
            <View style={styles.card}>

              <Text style={styles.name}>
                {item.fullName || "Unknown Student"}
              </Text>

              <Text style={styles.detail}>
                Matric: {item.matricNumber || "-"}
              </Text>

              <Text style={styles.detail}>
                Department: {item.department || "-"}
              </Text>

              <Text style={styles.detail}>
                Status: {item.status || "-"}
              </Text>

              <Text style={styles.detail}>
                Date: {item.date || "-"}
              </Text>

              <Text style={styles.detail}>
                Time: {item.time || "-"}
              </Text>

            </View>
          )}
        />
      )}

    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: "#F5FAFC",
  },

  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FAFC",
  },

  loadingText: {
    marginTop: 10,
    color: "#666",
  },
 headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },

  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#0B6E99",
    flex: 1,
  },

  exportButton: {
    backgroundColor: "#0B6E99",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    minWidth: 100,
    alignItems: "center",
    justifyContent: "center",
  },

  exportButtonDisabled: {
    opacity: 0.7,
  },

  exportButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 13,
  },

  listContent: {
    paddingBottom: 20,
  },

  card: {
    backgroundColor: "#fff",
    padding: 15,
    marginBottom: 10,
    borderRadius: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },

  name: {
    fontSize: 17,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#0B6E99",
  },

  detail: {
    fontSize: 14,
    marginBottom: 4,
    color: "#333",
  },

  emptyText: {
    fontSize: 16,
    color: "#888",
    textAlign: "center",
    marginTop: 30,
  },
});

{/*import React, { useState, useEffect } from "react";
import { View, Text, StyleSheet, FlatList, ActivityIndicator, TouchableOpacity, Alert } from "react-native";
import { db } from "../firebaseConfig";
import { collection, getDocs } from "firebase/firestore";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export default function AttendanceHistoryScreen() {
    const [attendanceRecords, setAttendanceRecords] = useState([]);
    const [loading, setLoading] = useState(true);
    const [exporting, setExporting] = useState(false);

    const fetchAttendance = async () => {
        try {
            setLoading(true);

            const querySnapshot = await getDocs(
                collection(db, "attendance")
            );

            const data = querySnapshot.docs.map(doc => ({
                id: doc.id,
                ...doc.data(),
            }));
            setAttendanceRecords(data);
        } catch (error) {
            console.log(error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchAttendance();
    }, []);

    const getTodayString = () => {
        const today = new Date();
        return today.toISOString().split("T")[0]; // "YYYY-MM-DD"
        // If your "date" field is stored differently (e.g. "21/09/2026"),
        // adjust this to match that format.
    };

    const exportTodayToPDF = async () => {
        const todayStr = getTodayString();
        const todaysRecords = attendanceRecords.filter(item => item.date === todayStr);

        if (todaysRecords.length === 0) {
            Alert.alert("No records", "No attendance records found for today.");
            return;
        }

        setExporting(true);
        try {
            const rowsHtml = todaysRecords.map(item =>`
                <tr>
                    <td>${item.fullName ?? ""}</td>
                    <td>${item.matricNumber ?? ""}</td>
                    <td>${item.department ?? ""}</td>
                    <td>${item.status ?? ""}</td>
                    <td>${item.time ?? ""}</td>
                </tr>
            `).join("");

            const html = `
                <html>
                    <head>
                        <style>
                            body { font-family: Helvetica, Arial, sans-serif; padding: 20px; }
                            h1 { font-size: 20px; margin-bottom: 4px; }
                            p { color: #555; margin-top: 0; margin-bottom: 20px; }
                            table { width: 100%; border-collapse: collapse; }
                            th, td { border: 1px solid #ddd; padding: 8px; font-size: 12px; text-align: left; }
                            th { background-color: #2563eb; color: #fff; }
                        </style>
                    </head>
                    <body>
                        <h1>AttendIQ — Attendance Record</h1>
                        <p>Date: ${todayStr}</p>
                        <table>
                            <tr>
                                <th>Name</th>
                                <th>Matric No.</th>
                                <th>Department</th>
                                <th>Status</th>
                                <th>Time</th>
                            </tr>
                            ${rowsHtml}
                        </table>
                    </body>
                </html>
            `;

            const { uri } = await Print.printToFileAsync({ html });

            const canShare = await Sharing.isAvailableAsync();
            if (canShare) {
                await Sharing.shareAsync(uri, {
                    mimeType: "application/pdf",
                    dialogTitle: "Today's Attendance Record",
                });
            } else {
                Alert.alert("Saved", `PDF saved at: ${uri}`);
            }
        } catch (error) {
            console.log(error);
            Alert.alert("Export failed", "Something went wrong while generating the PDF.");
        } finally {
            setExporting(false);
        }
    };
    
    if (loading) {
        return (
            <View style={styles.centered}>
                <ActivityIndicator size="large" />
            </View>
        );
    }

    return (
        <View style={styles.container}>
            <View style={styles.headerRow}>
                <Text style={styles.title}>Attendance History</Text>
                <TouchableOpacity
                    style={styles.exportButton}
                    onPress={exportTodayToPDF}
                    disabled={exporting}
                >
                    <Text style={styles.exportButtonText}>
                        {exporting ? "Exporting..." : "Export Today (PDF)"}
                    </Text>
                </TouchableOpacity>
            </View>

            {attendanceRecords.length === 0 ? (
                <Text style={styles.emptyText}>No attendance records found.</Text>
            ) : (
                <FlatList
                    data={attendanceRecords}
                    keyExtractor={(item) => item.id}
                    renderItem={({ item }) => (
                        <View style={styles.card}>
                            <Text> Name: {item.fullName}</Text>
                            <Text> Matric: {item.matricNumber}</Text>
                            <Text> Department: {item.department}</Text>
                            <Text> Status: {item.status}</Text>
                            <Text> Date: {item.date}</Text>
                            <Text> Time: {item.time}</Text>
                        </View>
                    )}
                />
            )}
        </View>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, padding: 20 },
    centered: { flex: 1, justifyContent: "center", alignItems: "center" },
    headerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    title: { fontSize: 24, fontWeight: "bold" },
    exportButton: {
        backgroundColor: "#2563eb",
        paddingVertical: 8,
        paddingHorizontal: 14,
        borderRadius: 8,
    },
    exportButtonText: { color: "#fff", fontWeight: "600", width: 50 },
    card: {
        backgroundColor: "#fff",
        padding: 15,
        marginBottom: 10,
        borderRadius: 10,
        elevation: 3,
    },
    emptyText: { fontSize: 16, color: "#888", textAlign: "center", marginTop: 20 },
});*/}